services:
  vault-injector:
    build: .
    container_name: vault-injector
    restart: always
    env_file:
      - .env
    volumes:
      - type: bind
        source: ${TARGET_HOST_FILE}
        target: /secrets/secrets.env